#!/bin/sh
set -e

if [ "$#" -le 2 ]; then
	echo "$0 DISTRO_NAME RELEASE VERSION [SRC_DIR] [PACKAGE_DIR]"
	echo "for example"
	echo "$0 ubuntu precise 2.3.0"
	exit
fi

DISTRO_NAME=$1
RELEASE=$2
DISTRO_DIR=$PWD/$RELEASE
VERSION=$3
SRC=$4
SKELETON=$PWD/skeleton
PACKAGE=$5
NIGHTLY_DATE=`date +%Y-%m-%d`

if [ ! -d $DISTRO_DIR ]; then
	echo "directory $DISTRO_DIR doesn't exist"
	exit
fi

#TODO check that DISTRO_NAME exists on the remote server

if [ -z "$SRC" -o ! -d "$SRC" ]; then
	SRC=`mktemp -d`
fi

cd $SRC
if [ ! -d $SRC/.git ]; then
	git clone https://github.com/facebook/hhvm.git $SRC
	git submodule update --init
	CMAKE_LIBRARY_PATH="/usr/lib/hhvm/" HPHP_HOME=$SRC cmake .
fi

if [ "$VERSION" = "nightly" ]; then
	git checkout master
	perl -pi -e 's/[0-9.]*-dev/nightly-'$NIGHTLY_DATE/ hphp/version
	perl -pi -e 's/[0-9.]*-dev/nightly-'$NIGHTLY_DATE/ hphp/system/idl/constants.idl.json
else
	git checkout HHVM-$VERSION
	if ! grep -q $VERSION hphp/version; then
		echo "$VERSION isn't in hphp/version"
		exit
	fi
	if ! grep -q $VERSION hphp/system/idl/constants.idl.json; then
		echo "$VERSION isn't in hphp/system/idl/constants.idl.json"
		exit
	fi
fi

if [ ! -f $SRC/hphp/hhvm/hhvm ]; then
	HPHP_HOME=$SRC make -j 8
	if [ ! -f $SRC/hphp/hhvm/hhvm ]; then
		echo "$SRC/hphp/hhvm/hhvm doesn't exist"
		exit
	fi
fi

$SRC/hphp/hhvm/hhvm --version | grep -q $VERSION
if [ $? -ne 0 ]; then
	echo "Wrong version was built?"
	exit
fi

if [ -z "$PACKAGE" -o ! -d "$PACKAGE" ]; then
	PACKAGE=`mktemp -d`
fi
echo "Packaging in $PACKAGE"
cd $PACKAGE

if [ ! -d $PACKAGE/root ]; then
	mkdir $PACKAGE/root
	cp -R $SKELETON/* $PACKAGE/root/
	cp -R $DISTRO_DIR/* $PACKAGE/root/
	cp $SRC/hphp/hhvm/hhvm $PACKAGE/root/usr/bin/
	chmod 755 $PACKAGE/root/usr/bin/hhvm
	if [ "$VERSION" = "nightly" ]; then
		perl -pi -e "s/Conflicts: .*\n//" $PACKAGE/root/DEBIAN/control
		perl -pi -e "s/Provides: .*\n//" $PACKAGE/root/DEBIAN/control
		perl -pi -e "s/Replaces: .*\n//" $PACKAGE/root/DEBIAN/control
		perl -pi -e "s/Package: hhvm/Package: hhvm-nightly\nConflicts: hhvm\nProvides: hhvm\nReplaces: hhvm/" $PACKAGE/root/DEBIAN/control
		perl -pi -e "s/Version: .*/Version: $NIGHTLY_DATE~$RELEASE/" $PACKAGE/root/DEBIAN/control
	else	
		perl -pi -e "s/Version: .*/Version: $VERSION~$RELEASE/" $PACKAGE/root/DEBIAN/control
	fi
	sudo chown -R root:root $PACKAGE/root
	sudo chown -R www-data:www-data $PACKAGE/root/var/log/hhvm/
	sudo chown -R www-data:www-data $PACKAGE/root/var/run/hhvm/
fi

dpkg -b $PACKAGE/root/ hhvm_${VERSION}_amd64.deb
dpkg-sig -k 452A652F --sign builder $PACKAGE/hhvm_${VERSION}_amd64.deb

rsync -avz hiphop@dl.hhvm.com:data/$DISTRO_NAME/ $PACKAGE/staging/

sudo apt-get install reprepro
#TODO figure out how the -b options works
cd $PACKAGE/staging
reprepro includedeb $RELEASE $PACKAGE/hhvm_${VERSION}_amd64.deb
cd -

rsync -avz $PACKAGE/staging/ hiphop@dl.hhvm.com:data/$DISTRO_NAME/
ssh hiphop@dl.hhvm.com "/home/hiphop/trigger-hiphop"
