#!/bin/sh

if [ "$#" -ne 1 -a "$#" -ne 2 ]; then
echo "$0 <version like 2.3.1>"
        exit
fi

ver=$1
arch=`uname -m`

mkdir -p staging/$arch

set -e

# Some flags that could be added to this command:
#   -c - Clean up work files when done
#   --check - run the tests when finished
#   -f - Force build if already built (shouldn't be needed since pkgrel updates
#                                           count as a new version)
HHVM_VERSION=${ver} makepkg -s

mv hhvm-${ver}-1-$arch.pkg.tar.xz staging/$arch
repo-add staging/$arch/hhvm.db.tar.gz staging/$arch/*.pkg.tar.xz

#rsync -avz staging/ hiphop@dl.hhvm.com:data/archlinux/
