#!/bin/bash

# php5-cli uses a priority of 50, so we pick a much smaller number
if [ -f /usr/sbin/update-alternatives ]; then
	/usr/sbin/update-alternatives --install /usr/bin/php php /usr/bin/hhvm 10
fi
if [ -f /usr/bin/update-alternatives ]; then
	/usr/bin/update-alternatives --install /usr/bin/php php /usr/bin/hhvm 10
fi

echo "********************************************************************"
echo "* HHVM is installed. Here are some more things you might want to do:"
echo "* "
echo "* Configure your webserver to use HHVM:"
echo "* $ sudo /usr/share/hhvm/install_fastcgi.sh"
echo "* $ sudo /etc/init.d/nginx restart"
echo "* $ sudo /etc/init.d/apache restart"
echo "* $ sudo /etc/init.d/hhvm restart"
echo "* "
echo "* Run command line scripts with HHVM:"
echo "* $ hhvm whatever.php"
echo "* "
echo "* Use HHVM for /usr/bin/php even if you have php-cli installed:"
echo "* $ sudo /usr/bin/update-alternatives --install /usr/bin/php php /usr/bin/hhvm 60"
echo "********************************************************************"
