#!/bin/bash

set -e 

if [ -f /etc/init.d/hhvm ]
then
	/etc/init.d/hhvm stop
fi

echo "********************************************************************"
echo "* HHVM is being removed. You can remove it from your webserver with:"
echo "* "
echo "* $ /usr/share/hhvm/uninstall_fastcgi.sh"
echo "* $ /etc/init.d/nginx restart"
echo "* $ /etc/init.d/apache restart"
echo "********************************************************************"
