#!/bin/bash

echo "********************************************************************"
echo "* HHVM is installed."
echo "*"
echo "* The best way to get started is to use HHVM's built-in webserver: "
echo "*"
echo "* $ hhvm -m server -p 8080"
echo "*"
echo "* Running command-line scripts with HHVM requires no special setup:"
echo "*"
echo "* $ hhvm example.hack"
echo "*"
echo "* FastCGI is also supported; see https://docs.hhvm.com/hhvm/advanced-usage/fastCGI"
echo "*"
echo "********************************************************************"

RUN_AS_USER="www-data"
RUN_AS_GROUP="www-data"

if [ -f /etc/default/hhvm ]; then
    . /etc/default/hhvm
fi

install -d -m 755 -o $RUN_AS_USER -g $RUN_AS_GROUP /var/run/hhvm
install -d -m 01733 /var/lib/hhvm/sessions

if which invoke-rc.d >/dev/null 2>&1; then
    invoke-rc.d hhvm start
fi
