#!/bin/bash
#
# Copyright (c) 2017-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

set -ex 

VERSION=5.5.0

cd /tmp
wget -q http://mirrors.ocf.berkeley.edu/gnu/gcc/gcc-$VERSION/gcc-$VERSION.tar.gz
tar zxf gcc-$VERSION.tar.gz

unset CFLAGS
unset CXXFLAGS
unset LDFLAGS
env

cd gcc-$VERSION
contrib/download_prerequisites

mkdir ../objdir
cd ../objdir

unset CFLAGS
unset CXXFLAGS
unset CFLAGS_FOR_BUILD
unset CXXFLAGS_FOR_BUILD
unset CFLAGS_FOR_TARGET
unset CXXFLAGS_FOR_TARGET
$(pwd)/../gcc-$VERSION/configure \
  --prefix=/opt/hhvm-build-deps \
  --enable-languages=c,c++ \
  --disable-multilib \
  --with-default-libstdcxx-abi=gcc4-compatible \
  --disable-libstdcxx-dual-abi
make -j8
make install
cd /tmp
