#!/bin/bash
#
# Copyright (c) 2017-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

set -ex 

cd /tmp
VERSION=4.5.0

wget -q https://github.com/jemalloc/jemalloc/releases/download/$VERSION/jemalloc-$VERSION.tar.bz2
tar jxf jemalloc-$VERSION.tar.bz2
cd jemalloc-$VERSION

CFLAGS=-fPIC CXXFLAGS=-fPIC ./configure \
  --prefix=/opt/hhvm-build-deps \
  --enable-static \
  --disable-shared
make -j8
make install
