#!/bin/bash
#
# Copyright (c) 2017-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

VERSION=4.5.0
BUILD_VER=1

set -ex 

PKG_NAME=jemalloc
CACHE_TARBALL="/var/nodist/${PKG_NAME}-${VERSION}-$(</opt/hhvm-distro-packaging/DISTRIBUTION)${BUILD_VER}.tar.bz2"
PKG_DIR=$(mktemp -d)

cd /tmp
if [ -e "$CACHE_TARBALL" ]; then
  echo "Using ${CACHE_TARBALL}..."
  cd /
  tar xfv "$CACHE_TARBALL"
  exit 0
fi

wget -q https://github.com/jemalloc/jemalloc/releases/download/$VERSION/jemalloc-$VERSION.tar.bz2
tar jxf jemalloc-$VERSION.tar.bz2
cd jemalloc-$VERSION

CFLAGS=-fPIC CXXFLAGS=-fPIC ./configure \
  --prefix=/opt/hhvm-build-deps \
  --enable-static \
  --disable-shared
make -j8
make install "DESTDIR=${PKG_DIR}"

cd "${PKG_DIR}"
mkdir -p "$(dirname "$CACHE_TARBALL")"
tar jcf "$CACHE_TARBALL" *
cd /
tar xfv "$CACHE_TARBALL"
