#!/bin/bash
#
# Copyright (c) 2017-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

VERSION=0.3.5
BUILD_VER=1

set -ex 

PKG_NAME=glog
CACHE_TARBALL="/var/nodist/${PKG_NAME}-${VERSION}-$(</opt/hhvm-distro-packaging/DISTRIBUTION)${BUILD_VER}.tar.bz2"
PKG_DIR=$(mktemp -d)

cd /tmp
if [ -e "$CACHE_TARBALL" ]; then
  echo "Using ${CACHE_TARBALL}..."
  cd /
  tar xfv "$CACHE_TARBALL"
  exit 0
fi

git clone https://github.com/google/glog.git google-glog
cd google-glog
git checkout v$VERSION

cmake . \
  -DWITH_GFLAGS=OFF \
  -DBUILD_SHARED_LIBS=OFF \
  -DCMAKE_C_FLAGS="-fPIC" \
  -DCMAKE_CXX_FLAGS="-fPIC" \
  -DCMAKE_C_COMPILER=gcc \
  -DCMAKE_CXX_COMPILER=g++ \
  -DCMAKE_INSTALL_PREFIX=/opt/hhvm-build-deps
make -j8
make install DESTDIR="${PKG_DIR}"

cd "${PKG_DIR}"
mkdir -p "$(dirname "$CACHE_TARBALL")"
tar jcf "$CACHE_TARBALL" *
cd /
tar xfv "$CACHE_TARBALL"
